# Generated by Django 2.0.2 on 2018-02-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem', models.CharField(max_length=500)),
                ('solution', models.CharField(max_length=2000)),
                ('type', models.IntegerField(choices=[(0, 'Dataset'), (1, 'Method'), (2, 'Theory')])),
                ('methods', models.ManyToManyField(to='paper.Method')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='orig_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='Original paper'),
        ),
    ]
