# Generated by Django 2.0.2 on 2018-02-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=3200)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=500)),
                ('solution', models.TextField(max_length=2000)),
                ('text_url', models.URLField()),
                ('code_url', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('date_published', models.DateField(verbose_name='publication date')),
                ('type', models.IntegerField(choices=[(0, 'Dataset'), (1, 'Method'), (2, 'Theory')])),
                ('authors', models.ManyToManyField(to='paper.Author')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Conference')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='orig_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='Original paper'),
        ),
    ]
