# Generated by Django 2.0.2 on 2018-02-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='problem',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='solution',
            field=models.TextField(max_length=2000),
        ),
    ]
