# Generated by Django 2.0.2 on 2018-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.CharField(max_length=3200),
        ),
    ]
