# Generated by Django 2.0.2 on 2018-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20180207_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(max_length=3200),
        ),
    ]
