# Generated by Django 2.0.2 on 2018-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20180206_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='methods',
            field=models.ManyToManyField(blank=True, to='paper.Method'),
        ),
    ]
