# Generated by Django 2.0.2 on 2018-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20180206_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='short_title',
            field=models.CharField(default='sh', max_length=20),
            preserve_default=False,
        ),
    ]
