# Generated by Django 2.0.7 on 2018-07-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('to_complete', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3200)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=3200)),
                ('visual_description', models.ImageField(blank=True, upload_to='uploads')),
                ('to_complete', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('to_complete', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=500)),
                ('solution', models.TextField(max_length=2000)),
                ('text_url', models.URLField()),
                ('code_url', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('date_published', models.DateField(verbose_name='publication date')),
                ('to_complete', models.TextField(blank=True, max_length=2000)),
                ('authors', models.ManyToManyField(through='elements.Authorship', to='elements.Author')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3200)),
            ],
        ),
        migrations.CreateModel(
            name='TextResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100)),
                ('detailed_description', models.TextField(max_length=3000)),
                ('visual_description', models.ImageField(blank=True, upload_to='uploads')),
                ('to_complete', models.TextField(blank=True, max_length=2000)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='ValueResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('configuration', models.TextField(blank=True, max_length=1000)),
                ('to_complete', models.TextField(blank=True, max_length=2000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Dataset')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Method')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Metric')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='types',
            field=models.ManyToManyField(to='elements.PaperType'),
        ),
        migrations.AddField(
            model_name='method',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper', verbose_name='Original elements'),
        ),
        migrations.AddField(
            model_name='link',
            name='dst_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_paper', to='elements.Paper'),
        ),
        migrations.AddField(
            model_name='link',
            name='src_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_paper', to='elements.Paper'),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.LinkType'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper'),
        ),
    ]
