# Generated by Django 2.0.4 on 2018-05-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='to_complete',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='method',
            name='to_complete',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='metric',
            name='to_complete',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='paper',
            name='to_complete',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='textresult',
            name='to_complete',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='valueresult',
            name='to_complete',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
