# Generated by Django 2.0.4 on 2018-05-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='visual_description',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
