# Generated by Django 2.0.3 on 2018-03-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20180329_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('original_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elements.Dataset'),
            preserve_default=False,
        ),
    ]
