# Generated by Django 2.0.3 on 2018-04-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_result_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='short_title',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='original_paper',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='orig_paper',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='short_title',
            new_name='short_name',
        ),
    ]
