# Generated by Django 2.0.3 on 2018-04-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_auto_20180401_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3200)),
                ('dst_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_paper', to='elements.Paper')),
                ('src_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_paper', to='elements.Paper')),
            ],
        ),
    ]
