# Generated by Django 2.0.3 on 2018-04-02 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3200)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.IntegerField(choices=[(0, 'Dataset'), (1, 'Method'), (2, 'Theory'), (3, 'Review')]),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='elements.LinkType'),
            preserve_default=False,
        ),
    ]
