# Generated by Django 2.0.3 on 2018-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_auto_20180402_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3200)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='type',
        ),
        migrations.AddField(
            model_name='paper',
            name='type',
            field=models.ManyToManyField(to='elements.PaperType'),
        ),
    ]
