# Generated by Django 2.0.4 on 2018-04-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_auto_20180430_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100)),
                ('detailed_description', models.TextField(max_length=3000)),
                ('visual_description', models.ImageField(blank=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='ValueResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('configuration', models.TextField(blank=True, max_length=1000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Dataset')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Method')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Metric')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='result',
            name='method',
        ),
        migrations.RemoveField(
            model_name='result',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='result',
            name='paper',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='type',
            new_name='types',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='valueresult',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper'),
        ),
        migrations.AddField(
            model_name='textresult',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Paper'),
        ),
    ]
